spring:
  application:
    name: ms-account-reservation

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/account_reservation}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: ${FORMAT_SQL:true}

server:
  port: ${SERVER_PORT:8080}