spring:
  application:
    name: ms-account-reservation

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}
        format_sql: ${FORMAT_SQL:true}

  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:db-changelog-master.xml

server:
  port: ${SERVER_PORT}

logging:
  level:
    liquibase: DEBUG
    org.springframework.boot.autoconfigure.liquibase: DEBUG



