# Переменные окружения для подключения к БД
DATABASE_URL=jdbc:postgresql://localhost:5432/account_reservation
DATABASE_USER=postgres
DATABASE_PASSWORD=postgres
DATABASE_DRIVER=org.postgresql.Driver

# Параметры JPA
DDL_AUTO=validate
SHOW_SQL=true
HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
FORMAT_SQL=true

# Порт сервера
SERVER_PORT=8080